### ISSUE TITLE
Shouldn't formatters specify Accept and Content-type headers?

### ISSUE THREAD

**Issue by voxpelli** [hugowetterberg/http_client#1]
If a formatter has been specified it will define how the data is serialized and deserialized.
Shouldn't those formatters as well specify which Accept and Content-type headers that should be sent?

**Comment by hugowetterberg** [comment]
Yes, they definitely should, and it's one of those things that I've been thinking to add for a while now. Actually I think that I once did add it, but sort of lost the code.
