### ISSUE TITLE
Content length not UTF-8 aware

### ISSUE THREAD

**Issue by simme** [hugowetterberg/http_client#2]
Content encoded as UTF-8 get the wrong content length due to use of strlen which is not UTF-8 safe.

Replace strlen with mb_strlen or strlen(utf8_encode($str)) to remedy the issue. Probably should make sure the content is actually UTF-8 encoded too before strlen'ing it!

**Comment by hugowetterberg** [comment]
That's intentional, content length has nothing to do with the number of characters but the number of bytes. As strlen counts double-byte charactersas two bytes it gives us the correct number of bytes regardless of whether the string is UTF8 or not.

**Comment by simme** [comment]
Ah, that's true. My bad
